/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author Rodrigo
 */
public class ConsultaPapel extends javax.swing.JFrame {

    /**
     * Creates new form ConsultaPapel
     */
    public ConsultaPapel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        jCheckBox7 = new javax.swing.JCheckBox();
        jCheckBox8 = new javax.swing.JCheckBox();
        jCheckBox9 = new javax.swing.JCheckBox();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        __etqFechaConMov = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        __chkEntrDesdeMov = new javax.swing.JCheckBox();
        __chkSaliDesdeMov = new javax.swing.JCheckBox();
        __chkDevoluDesdeMov = new javax.swing.JCheckBox();
        jLabel14 = new javax.swing.JLabel();
        __clvDesdeMov = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        __dateDesdeMov = new com.toedter.calendar.JDateChooser();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        __etqDocuDesdeMov = new javax.swing.JTextField();
        __etqPediDesdeMov = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        __etqProvDesdeMov = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        __etqOrdenProdDesdeMov = new javax.swing.JTextField();
        __etqOrdenCompraDesdeMov = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        __cmbPropiDesdeMovi = new javax.swing.JComboBox();
        jPanel11 = new javax.swing.JPanel();
        __chkTurno1DesdeMov = new javax.swing.JCheckBox();
        __chkTurno2DesdeMov = new javax.swing.JCheckBox();
        __chkTurno3DesdeMov = new javax.swing.JCheckBox();
        jPanel8 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        __chkEntrHastaMov = new javax.swing.JCheckBox();
        __chkSaliHastaMov = new javax.swing.JCheckBox();
        __chkDevoluHastaMov = new javax.swing.JCheckBox();
        jLabel22 = new javax.swing.JLabel();
        __Alto_10 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        __dateHastaMov = new com.toedter.calendar.JDateChooser();
        __etqDocuHastaMov = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        __etqProvHastaMov = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        __cmbPropiHastaMovi = new javax.swing.JComboBox();
        __etqOrdenCompraHastaMov = new javax.swing.JTextField();
        __etqOrdenProdHastaMov = new javax.swing.JTextField();
        __etqPediHastaMov = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        __chkTurno1HastaMov = new javax.swing.JCheckBox();
        __chkTurno2HastaMov = new javax.swing.JCheckBox();
        __chkTurno3HastaMov = new javax.swing.JCheckBox();
        jLabel29 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        __CANCELARCONMOV = new javax.swing.JButton();
        __NUEVACONSULTAMOV = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        __etqFechaConDocu = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        __etqDocuDesdeDocu = new javax.swing.JTextField();
        __dateDesdeDocu = new com.toedter.calendar.JDateChooser();
        __etqMoviDesdeDocu = new javax.swing.JTextField();
        jPanel14 = new javax.swing.JPanel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        __etqDocuHastaDocu = new javax.swing.JTextField();
        __dateHastaDocu = new com.toedter.calendar.JDateChooser();
        __etqMoviHastaDocu = new javax.swing.JTextField();
        __NUEVACONSULTAMOV1 = new javax.swing.JButton();
        __CANCELARCONMOV1 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Turno:"));

        jCheckBox7.setText("Turno 1");
        jCheckBox7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox7ActionPerformed(evt);
            }
        });

        jCheckBox8.setText("Turno 2");
        jCheckBox8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox8ActionPerformed(evt);
            }
        });

        jCheckBox9.setText("Turno 3");
        jCheckBox9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jCheckBox9)
                    .addComponent(jCheckBox8)
                    .addComponent(jCheckBox7))
                .addGap(28, 28, 28))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jCheckBox7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jCheckBox9))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel13.setFont(new java.awt.Font("Papyrus", 0, 14)); // NOI18N
        jLabel13.setText("Para Realizar la Consulta Ingresa los Parametros que Necesitas y Finaliza con la Tecla F8");

        __etqFechaConMov.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        __etqFechaConMov.setText("DD/MM/AAAA");

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Desde:"));

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder("Tipo de Movimiento:"));

        __chkEntrDesdeMov.setText("Entrada");
        __chkEntrDesdeMov.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                __chkEntrDesdeMovActionPerformed(evt);
            }
        });

        __chkSaliDesdeMov.setText("Salida");
        __chkSaliDesdeMov.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                __chkSaliDesdeMovActionPerformed(evt);
            }
        });

        __chkDevoluDesdeMov.setText("Devolución");
        __chkDevoluDesdeMov.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                __chkDevoluDesdeMovActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(__chkDevoluDesdeMov)
                    .addComponent(__chkSaliDesdeMov)
                    .addComponent(__chkEntrDesdeMov))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(__chkEntrDesdeMov)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(__chkSaliDesdeMov)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(__chkDevoluDesdeMov))
        );

        jLabel14.setFont(new java.awt.Font("Papyrus", 0, 14)); // NOI18N
        jLabel14.setText("Clave de Papel:");

        __clvDesdeMov.setFont(new java.awt.Font("Papyrus", 0, 14)); // NOI18N

        jLabel15.setFont(new java.awt.Font("Papyrus", 0, 14)); // NOI18N
        jLabel15.setText("Fecha:");

        jLabel16.setFont(new java.awt.Font("Papyrus", 0, 14)); // NOI18N
        jLabel16.setText("Documento:");

        jLabel17.setFont(new java.awt.Font("Papyrus", 0, 14)); // NOI18N
        jLabel17.setText("Pedido:");

        __etqDocuDesdeMov.setFont(new java.awt.Font("Papyrus", 0, 14)); // NOI18N

        __etqPediDesdeMov.setFont(new java.awt.Font("Papyrus", 0, 14)); // NOI18N

        jLabel18.setFont(new java.awt.Font("Papyrus", 0, 14)); // NOI18N
        jLabel18.setText("Orden de Producción:");

        jLabel19.setFont(new java.awt.Font("Papyrus", 0, 14)); // NOI18N
        jLabel19.setText("Prov/Clie:");

        __etqProvDesdeMov.setFont(new java.awt.Font("Papyrus", 0, 14)); // NOI18N

        jLabel20.setFont(new java.awt.Font("Papyrus", 0, 14)); // NOI18N
        jLabel20.setText("Orden de Compra:");

        __etqOrdenProdDesdeMov.setFont(new java.awt.Font("Papyrus", 0, 14)); // NOI18N

        __etqOrdenCompraDesdeMov.setFont(new java.awt.Font("Papyrus", 0, 14)); // NOI18N

        jLabel21.setFont(new java.awt.Font("Papyrus", 0, 14)); // NOI18N
        jLabel21.setText("Propietario:");

        __cmbPropiDesdeMovi.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecciona....." }));
        __cmbPropiDesdeMovi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                __cmbPropiDesdeMoviActionPerformed(evt);
            }
        });

        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder("Turno:"));

        __chkTurno1DesdeMov.setText("Turno 1");
        __chkTurno1DesdeMov.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                __chkTurno1DesdeMovActionPerformed(evt);
            }
        });

        __chkTurno2DesdeMov.setText("Turno 2");
        __chkTurno2DesdeMov.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                __chkTurno2DesdeMovActionPerformed(evt);
            }
        });

        __chkTurno3DesdeMov.setText("Turno 3");
        __chkTurno3DesdeMov.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                __chkTurno3DesdeMovActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(__chkTurno3DesdeMov)
                    .addComponent(__chkTurno2DesdeMov)
                    .addComponent(__chkTurno1DesdeMov))
                .addGap(28, 28, 28))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addComponent(__chkTurno1DesdeMov)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(__chkTurno2DesdeMov)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(__chkTurno3DesdeMov))
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16)))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(__etqPediDesdeMov, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel19)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(__etqProvDesdeMov, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(__clvDesdeMov)
                        .addComponent(__dateDesdeMov, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(__etqDocuDesdeMov, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(__etqOrdenProdDesdeMov, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(__etqOrdenCompraDesdeMov, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel21)
                        .addGap(38, 38, 38))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(__cmbPropiDesdeMovi, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(__clvDesdeMov, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(__dateDesdeMov, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(__etqDocuDesdeMov, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16))))
                .addGap(19, 19, 19)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(__etqPediDesdeMov, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19)
                    .addComponent(__etqProvDesdeMov, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(__etqOrdenProdDesdeMov, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(__etqOrdenCompraDesdeMov, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(__cmbPropiDesdeMovi, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("Hasta:"));

        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder("Tipo de Movimiento:"));

        __chkEntrHastaMov.setText("Entrada");
        __chkEntrHastaMov.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                __chkEntrHastaMovActionPerformed(evt);
            }
        });

        __chkSaliHastaMov.setText("Salida");
        __chkSaliHastaMov.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                __chkSaliHastaMovActionPerformed(evt);
            }
        });

        __chkDevoluHastaMov.setText("Devolución");
        __chkDevoluHastaMov.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                __chkDevoluHastaMovActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(__chkDevoluHastaMov)
                    .addComponent(__chkSaliHastaMov)
                    .addComponent(__chkEntrHastaMov))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addComponent(__chkEntrHastaMov)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(__chkSaliHastaMov)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(__chkDevoluHastaMov))
        );

        jLabel22.setFont(new java.awt.Font("Papyrus", 0, 14)); // NOI18N
        jLabel22.setText("Clave de Papel:");

        __Alto_10.setFont(new java.awt.Font("Papyrus", 0, 14)); // NOI18N

        jLabel23.setFont(new java.awt.Font("Papyrus", 0, 14)); // NOI18N
        jLabel23.setText("Fecha:");

        __etqDocuHastaMov.setFont(new java.awt.Font("Papyrus", 0, 14)); // NOI18N

        jLabel24.setFont(new java.awt.Font("Papyrus", 0, 14)); // NOI18N
        jLabel24.setText("Documento:");

        jLabel25.setFont(new java.awt.Font("Papyrus", 0, 14)); // NOI18N
        jLabel25.setText("Prov/Clie:");

        __etqProvHastaMov.setFont(new java.awt.Font("Papyrus", 0, 14)); // NOI18N

        jLabel26.setFont(new java.awt.Font("Papyrus", 0, 14)); // NOI18N
        jLabel26.setText("Propietario:");

        __cmbPropiHastaMovi.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecciona....." }));
        __cmbPropiHastaMovi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                __cmbPropiHastaMoviActionPerformed(evt);
            }
        });

        __etqOrdenCompraHastaMov.setFont(new java.awt.Font("Papyrus", 0, 14)); // NOI18N

        __etqOrdenProdHastaMov.setFont(new java.awt.Font("Papyrus", 0, 14)); // NOI18N

        __etqPediHastaMov.setFont(new java.awt.Font("Papyrus", 0, 14)); // NOI18N

        jLabel27.setFont(new java.awt.Font("Papyrus", 0, 14)); // NOI18N
        jLabel27.setText("Orden de Producción:");

        jLabel28.setFont(new java.awt.Font("Papyrus", 0, 14)); // NOI18N
        jLabel28.setText("Orden de Compra:");

        jPanel12.setBorder(javax.swing.BorderFactory.createTitledBorder("Turno:"));

        __chkTurno1HastaMov.setText("Turno 1");
        __chkTurno1HastaMov.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                __chkTurno1HastaMovActionPerformed(evt);
            }
        });

        __chkTurno2HastaMov.setText("Turno 2");
        __chkTurno2HastaMov.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                __chkTurno2HastaMovActionPerformed(evt);
            }
        });

        __chkTurno3HastaMov.setText("Turno 3");
        __chkTurno3HastaMov.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                __chkTurno3HastaMovActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(__chkTurno3HastaMov)
                    .addComponent(__chkTurno2HastaMov)
                    .addComponent(__chkTurno1HastaMov))
                .addGap(28, 28, 28))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addComponent(__chkTurno1HastaMov)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(__chkTurno2HastaMov)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(__chkTurno3HastaMov))
        );

        jLabel29.setFont(new java.awt.Font("Papyrus", 0, 14)); // NOI18N
        jLabel29.setText("Pedido:");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jLabel29)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(__etqPediHastaMov, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(227, Short.MAX_VALUE))
            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel8Layout.createSequentialGroup()
                    .addGap(3, 3, 3)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel8Layout.createSequentialGroup()
                            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel8Layout.createSequentialGroup()
                                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(30, 30, 30)
                                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel22)
                                        .addComponent(jLabel23)
                                        .addComponent(jLabel24)))
                                .addGroup(jPanel8Layout.createSequentialGroup()
                                    .addGap(195, 195, 195)
                                    .addComponent(jLabel25)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(__etqProvHastaMov, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(__Alto_10)
                                    .addComponent(__dateHastaMov, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(__etqDocuHastaMov, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(jPanel8Layout.createSequentialGroup()
                            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel8Layout.createSequentialGroup()
                                    .addComponent(jLabel27)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(__etqOrdenProdHastaMov, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel8Layout.createSequentialGroup()
                                        .addComponent(jLabel28)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(__etqOrdenCompraHastaMov, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel8Layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel26)
                                    .addGap(28, 28, 28))
                                .addGroup(jPanel8Layout.createSequentialGroup()
                                    .addGap(18, 18, 18)
                                    .addComponent(__cmbPropiHastaMovi, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGap(4, 4, 4)))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(__etqPediHastaMov, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel8Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel8Layout.createSequentialGroup()
                            .addGap(8, 8, 8)
                            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel22)
                                .addComponent(__Alto_10, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(__dateHastaMov, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel23))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(__etqDocuHastaMov, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel24))))
                    .addGap(19, 19, 19)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel25)
                        .addComponent(__etqProvHastaMov, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel8Layout.createSequentialGroup()
                            .addGap(18, 18, 18)
                            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel27)
                                .addComponent(__etqOrdenProdHastaMov, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel28)
                                .addComponent(__etqOrdenCompraHastaMov, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel8Layout.createSequentialGroup()
                            .addGap(7, 7, 7)
                            .addComponent(jLabel26)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(__cmbPropiHastaMovi, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(18, 18, 18)
                    .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jButton9.setText("Salir");

        __CANCELARCONMOV.setText("Cancelar");
        __CANCELARCONMOV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                __CANCELARCONMOVActionPerformed(evt);
            }
        });

        __NUEVACONSULTAMOV.setText("Nueva Consulta");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 8, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(__etqFechaConMov))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(__NUEVACONSULTAMOV)
                        .addGap(18, 18, 18)
                        .addComponent(__CANCELARCONMOV)
                        .addGap(18, 18, 18)
                        .addComponent(jButton9)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(__etqFechaConMov))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(__CANCELARCONMOV)
                    .addComponent(jButton9)
                    .addComponent(__NUEVACONSULTAMOV))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Movimiento", jPanel1);

        jLabel30.setFont(new java.awt.Font("Papyrus", 0, 14)); // NOI18N
        jLabel30.setText("Para Realizar la Consulta Ingresa los Parametros que Necesitas y Finaliza con la Tecla F8");

        __etqFechaConDocu.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        __etqFechaConDocu.setText("DD/MM/AAAA");

        jPanel13.setBorder(javax.swing.BorderFactory.createTitledBorder("Desde:"));

        jLabel32.setFont(new java.awt.Font("Papyrus", 0, 14)); // NOI18N
        jLabel32.setText("Documento:");

        jLabel31.setFont(new java.awt.Font("Papyrus", 0, 14)); // NOI18N
        jLabel31.setText("Fecha:");

        jLabel33.setFont(new java.awt.Font("Papyrus", 0, 14)); // NOI18N
        jLabel33.setText("Movimiento:");

        __etqDocuDesdeDocu.setFont(new java.awt.Font("Papyrus", 0, 14)); // NOI18N
        __etqDocuDesdeDocu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                __etqDocuDesdeDocuActionPerformed(evt);
            }
        });

        __etqMoviDesdeDocu.setFont(new java.awt.Font("Papyrus", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel33)
                    .addComponent(jLabel31)
                    .addComponent(jLabel32))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(__etqDocuDesdeDocu, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(__dateDesdeDocu, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(__etqMoviDesdeDocu, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(__etqDocuDesdeDocu, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel31)
                    .addComponent(__dateDesdeDocu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33)
                    .addComponent(__etqMoviDesdeDocu, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel14.setBorder(javax.swing.BorderFactory.createTitledBorder("Hasta:"));

        jLabel34.setFont(new java.awt.Font("Papyrus", 0, 14)); // NOI18N
        jLabel34.setText("Documento:");

        jLabel35.setFont(new java.awt.Font("Papyrus", 0, 14)); // NOI18N
        jLabel35.setText("Fecha:");

        jLabel36.setFont(new java.awt.Font("Papyrus", 0, 14)); // NOI18N
        jLabel36.setText("Movimiento:");

        __etqDocuHastaDocu.setFont(new java.awt.Font("Papyrus", 0, 14)); // NOI18N
        __etqDocuHastaDocu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                __etqDocuHastaDocuActionPerformed(evt);
            }
        });

        __etqMoviHastaDocu.setFont(new java.awt.Font("Papyrus", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel36)
                    .addComponent(jLabel35)
                    .addComponent(jLabel34))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(__etqDocuHastaDocu, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(__dateHastaDocu, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(__etqMoviHastaDocu, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel34)
                    .addComponent(__etqDocuHastaDocu, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel35)
                    .addComponent(__dateHastaDocu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel36)
                    .addComponent(__etqMoviHastaDocu, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        __NUEVACONSULTAMOV1.setText("Nueva Consulta");

        __CANCELARCONMOV1.setText("Cancelar");
        __CANCELARCONMOV1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                __CANCELARCONMOV1ActionPerformed(evt);
            }
        });

        jButton10.setText("Salir");

        jLabel37.setFont(new java.awt.Font("Papyrus", 0, 14)); // NOI18N
        jLabel37.setText(">>>>>>>>>>");

        jLabel38.setFont(new java.awt.Font("Papyrus", 0, 14)); // NOI18N
        jLabel38.setText(">>>>>>>>>>");

        jLabel39.setFont(new java.awt.Font("Papyrus", 0, 14)); // NOI18N
        jLabel39.setText(">>>>>>>>>>");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel30)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(__etqFechaConDocu))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(262, 262, 262)
                                .addComponent(__NUEVACONSULTAMOV1)
                                .addGap(18, 18, 18)
                                .addComponent(__CANCELARCONMOV1)
                                .addGap(18, 18, 18)
                                .addComponent(jButton10))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(72, 72, 72)
                                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel37)
                                    .addComponent(jLabel38)
                                    .addComponent(jLabel39))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 123, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(__etqFechaConDocu))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(jLabel37)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel39)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel38)))
                .addGap(51, 51, 51)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(__CANCELARCONMOV1)
                    .addComponent(jButton10)
                    .addComponent(__NUEVACONSULTAMOV1))
                .addContainerGap(129, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Documento", jPanel2);

        jMenu1.setText("Archivo");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0));
        jMenuItem1.setText("Regresar al menú anterior");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem12.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem12.setText("Alta de Papel");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem12);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setText("Consultas");
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Generar un reporte...");
        jMenu1.add(jMenuItem3);

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_W, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem4.setText("Cerrar Sesion");
        jMenu1.add(jMenuItem4);

        jMenuItem5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_W, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem5.setText("Salir del Sistema");
        jMenu1.add(jMenuItem5);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edicion");

        jMenuItem6.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem6.setText("Cambiar Fecha del Sistema");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem6);

        jMenuItem7.setText("Nuevo Usuario...");
        jMenu2.add(jMenuItem7);

        jMenuItem8.setText("Cambiar mi Contraseña");
        jMenu2.add(jMenuItem8);

        jMenuItem9.setText("Reporte de Usuarios");
        jMenu2.add(jMenuItem9);

        jMenuItem10.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        jMenuItem10.setText("Ayuda");
        jMenu2.add(jMenuItem10);

        jMenuItem11.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F10, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem11.setText("Acerca de...");
        jMenu2.add(jMenuItem11);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jCheckBox7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox7ActionPerformed

    private void jCheckBox8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox8ActionPerformed

    private void jCheckBox9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox9ActionPerformed

    private void __chkEntrDesdeMovActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event___chkEntrDesdeMovActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event___chkEntrDesdeMovActionPerformed

    private void __chkSaliDesdeMovActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event___chkSaliDesdeMovActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event___chkSaliDesdeMovActionPerformed

    private void __chkDevoluDesdeMovActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event___chkDevoluDesdeMovActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event___chkDevoluDesdeMovActionPerformed

    private void __cmbPropiDesdeMoviActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event___cmbPropiDesdeMoviActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event___cmbPropiDesdeMoviActionPerformed

    private void __chkTurno1DesdeMovActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event___chkTurno1DesdeMovActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event___chkTurno1DesdeMovActionPerformed

    private void __chkTurno2DesdeMovActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event___chkTurno2DesdeMovActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event___chkTurno2DesdeMovActionPerformed

    private void __chkTurno3DesdeMovActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event___chkTurno3DesdeMovActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event___chkTurno3DesdeMovActionPerformed

    private void __chkEntrHastaMovActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event___chkEntrHastaMovActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event___chkEntrHastaMovActionPerformed

    private void __chkSaliHastaMovActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event___chkSaliHastaMovActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event___chkSaliHastaMovActionPerformed

    private void __chkDevoluHastaMovActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event___chkDevoluHastaMovActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event___chkDevoluHastaMovActionPerformed

    private void __cmbPropiHastaMoviActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event___cmbPropiHastaMoviActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event___cmbPropiHastaMoviActionPerformed

    private void __chkTurno1HastaMovActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event___chkTurno1HastaMovActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event___chkTurno1HastaMovActionPerformed

    private void __chkTurno2HastaMovActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event___chkTurno2HastaMovActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event___chkTurno2HastaMovActionPerformed

    private void __chkTurno3HastaMovActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event___chkTurno3HastaMovActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event___chkTurno3HastaMovActionPerformed

    private void __CANCELARCONMOVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event___CANCELARCONMOVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event___CANCELARCONMOVActionPerformed

    private void __etqDocuDesdeDocuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event___etqDocuDesdeDocuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event___etqDocuDesdeDocuActionPerformed

    private void __etqDocuHastaDocuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event___etqDocuHastaDocuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event___etqDocuHastaDocuActionPerformed

    private void __CANCELARCONMOV1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event___CANCELARCONMOV1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event___CANCELARCONMOV1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultaPapel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultaPapel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultaPapel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultaPapel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultaPapel().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField __Alto_10;
    private javax.swing.JButton __CANCELARCONMOV;
    private javax.swing.JButton __CANCELARCONMOV1;
    private javax.swing.JButton __NUEVACONSULTAMOV;
    private javax.swing.JButton __NUEVACONSULTAMOV1;
    private javax.swing.JCheckBox __chkDevoluDesdeMov;
    private javax.swing.JCheckBox __chkDevoluHastaMov;
    private javax.swing.JCheckBox __chkEntrDesdeMov;
    private javax.swing.JCheckBox __chkEntrHastaMov;
    private javax.swing.JCheckBox __chkSaliDesdeMov;
    private javax.swing.JCheckBox __chkSaliHastaMov;
    private javax.swing.JCheckBox __chkTurno1DesdeMov;
    private javax.swing.JCheckBox __chkTurno1HastaMov;
    private javax.swing.JCheckBox __chkTurno2DesdeMov;
    private javax.swing.JCheckBox __chkTurno2HastaMov;
    private javax.swing.JCheckBox __chkTurno3DesdeMov;
    private javax.swing.JCheckBox __chkTurno3HastaMov;
    private javax.swing.JTextField __clvDesdeMov;
    private javax.swing.JComboBox __cmbPropiDesdeMovi;
    private javax.swing.JComboBox __cmbPropiHastaMovi;
    private com.toedter.calendar.JDateChooser __dateDesdeDocu;
    private com.toedter.calendar.JDateChooser __dateDesdeMov;
    private com.toedter.calendar.JDateChooser __dateHastaDocu;
    private com.toedter.calendar.JDateChooser __dateHastaMov;
    private javax.swing.JTextField __etqDocuDesdeDocu;
    private javax.swing.JTextField __etqDocuDesdeMov;
    private javax.swing.JTextField __etqDocuHastaDocu;
    private javax.swing.JTextField __etqDocuHastaMov;
    private javax.swing.JLabel __etqFechaConDocu;
    private javax.swing.JLabel __etqFechaConMov;
    private javax.swing.JTextField __etqMoviDesdeDocu;
    private javax.swing.JTextField __etqMoviHastaDocu;
    private javax.swing.JTextField __etqOrdenCompraDesdeMov;
    private javax.swing.JTextField __etqOrdenCompraHastaMov;
    private javax.swing.JTextField __etqOrdenProdDesdeMov;
    private javax.swing.JTextField __etqOrdenProdHastaMov;
    private javax.swing.JTextField __etqPediDesdeMov;
    private javax.swing.JTextField __etqPediHastaMov;
    private javax.swing.JTextField __etqProvDesdeMov;
    private javax.swing.JTextField __etqProvHastaMov;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton9;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JCheckBox jCheckBox8;
    private javax.swing.JCheckBox jCheckBox9;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
