/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author Favorito
 */
public class MovimientosPapel extends javax.swing.JFrame {

    /**
     * Creates new form MovimientosPapel
     */
    public MovimientosPapel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel2 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        __etqFechaEnt = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        __cmbPropietarioEntr = new javax.swing.JComboBox();
        jPanel4 = new javax.swing.JPanel();
        __chkTurno1Entr = new javax.swing.JCheckBox();
        __chkTurno2Entr = new javax.swing.JCheckBox();
        __chkTurno3Entr = new javax.swing.JCheckBox();
        __etqNoMoviEntr = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        __OrdenProduccionEntr = new javax.swing.JTextField();
        __OrdenCompraEntr = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        __tablaEntrada = new javax.swing.JTable();
        __ACEPTARENTRADA = new javax.swing.JButton();
        __CANCELARENTRADA = new javax.swing.JButton();
        __SALIRENTRADA = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        __etqFechaSal = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        __etqNoMoviSal = new javax.swing.JLabel();
        __cmdPropietarioSal = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        __OrdenProduccionSal = new javax.swing.JTextField();
        ___OrdenCompraSal = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        __chkTurno1Sal = new javax.swing.JCheckBox();
        __chkTurno2Sal = new javax.swing.JCheckBox();
        __chkTurno3Sal = new javax.swing.JCheckBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        __tablaSalida = new javax.swing.JTable();
        __ACEPTARSALIDA = new javax.swing.JButton();
        __CANCELARSALIDA = new javax.swing.JButton();
        __SALIRSALIDA = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        __etqFechaDev = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        __etqNoMoviDev = new javax.swing.JLabel();
        __cmbTipoPapelDev = new javax.swing.JComboBox();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        __OrdenProduccionDev = new javax.swing.JTextField();
        __OrdenCompraDev = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        __chkTurno1Dev = new javax.swing.JCheckBox();
        __chkTurno2Dev = new javax.swing.JCheckBox();
        __chkTurno3Dev = new javax.swing.JCheckBox();
        jScrollPane3 = new javax.swing.JScrollPane();
        __tablaDevoluciones = new javax.swing.JTable();
        __ACEPTARDEVOLUCIONES = new javax.swing.JButton();
        __CANCELARDEVOLUCIONES = new javax.swing.JButton();
        __SALIRDEVOLUCIONES = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        __etqFechaEnt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        __etqFechaEnt.setText("DD/MM/AAAA");

        jLabel2.setFont(new java.awt.Font("Papyrus", 1, 24)); // NOI18N
        jLabel2.setText("Entrada de Papel");

        jLabel4.setFont(new java.awt.Font("Papyrus", 0, 14)); // NOI18N
        jLabel4.setText("No. de Movimiento");

        __cmbPropietarioEntr.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecciona....." }));
        __cmbPropietarioEntr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                __cmbPropietarioEntrActionPerformed(evt);
            }
        });

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Turno:"));

        __chkTurno1Entr.setText("Turno 1");
        __chkTurno1Entr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                __chkTurno1EntrActionPerformed(evt);
            }
        });

        __chkTurno2Entr.setText("Turno 2");
        __chkTurno2Entr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                __chkTurno2EntrActionPerformed(evt);
            }
        });

        __chkTurno3Entr.setText("Turno 3");
        __chkTurno3Entr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                __chkTurno3EntrActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(__chkTurno3Entr)
                    .addComponent(__chkTurno2Entr)
                    .addComponent(__chkTurno1Entr))
                .addGap(28, 28, 28))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(__chkTurno1Entr)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(__chkTurno2Entr)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(__chkTurno3Entr))
        );

        __etqNoMoviEntr.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel5.setFont(new java.awt.Font("Papyrus", 0, 14)); // NOI18N
        jLabel5.setText("Orden de Compra:");

        jLabel6.setFont(new java.awt.Font("Papyrus", 0, 14)); // NOI18N
        jLabel6.setText("Propietario:");

        jLabel7.setFont(new java.awt.Font("Papyrus", 0, 14)); // NOI18N
        jLabel7.setText("Orden de Producción:");

        __OrdenProduccionEntr.setFont(new java.awt.Font("Papyrus", 0, 14)); // NOI18N

        __OrdenCompraEntr.setFont(new java.awt.Font("Papyrus", 0, 14)); // NOI18N

        __tablaEntrada.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "#", "Clave de Papel", "Cantidad", "Tipo de Llegada", " Presentación", "Costo (Kg/Millar)", "Total"
            }
        ));
        jScrollPane1.setViewportView(__tablaEntrada);

        __ACEPTARENTRADA.setText("Aceptar");

        __CANCELARENTRADA.setText("Cancelar");
        __CANCELARENTRADA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                __CANCELARENTRADAActionPerformed(evt);
            }
        });

        __SALIRENTRADA.setText("Salir");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(__cmbPropietarioEntr, 0, 108, Short.MAX_VALUE)
                                    .addComponent(__etqNoMoviEntr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(__OrdenCompraEntr, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(__OrdenProduccionEntr, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(__etqFechaEnt))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(__ACEPTARENTRADA)
                .addGap(18, 18, 18)
                .addComponent(__CANCELARENTRADA)
                .addGap(18, 18, 18)
                .addComponent(__SALIRENTRADA)
                .addGap(36, 36, 36))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4))
                            .addComponent(__etqNoMoviEntr, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(__OrdenProduccionEntr, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(__OrdenCompraEntr, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(__cmbPropietarioEntr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(14, 14, 14))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(__etqFechaEnt)
                        .addGap(26, 26, 26)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(__ACEPTARENTRADA)
                    .addComponent(__CANCELARENTRADA)
                    .addComponent(__SALIRENTRADA))
                .addGap(14, 14, 14))
        );

        panel2.addTab("1. Entrada", jPanel1);

        __etqFechaSal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        __etqFechaSal.setText("DD/MM/AAAA");

        jLabel3.setFont(new java.awt.Font("Papyrus", 1, 24)); // NOI18N
        jLabel3.setText("Salida de Papel");

        jLabel8.setFont(new java.awt.Font("Papyrus", 0, 14)); // NOI18N
        jLabel8.setText("No. de Movimiento");

        __etqNoMoviSal.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        __cmdPropietarioSal.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecciona....." }));
        __cmdPropietarioSal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                __cmdPropietarioSalActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Papyrus", 0, 14)); // NOI18N
        jLabel9.setText("Propietario:");

        jLabel10.setFont(new java.awt.Font("Papyrus", 0, 14)); // NOI18N
        jLabel10.setText("Orden de Compra:");

        jLabel11.setFont(new java.awt.Font("Papyrus", 0, 14)); // NOI18N
        jLabel11.setText("Orden de Producción:");

        __OrdenProduccionSal.setFont(new java.awt.Font("Papyrus", 0, 14)); // NOI18N

        ___OrdenCompraSal.setFont(new java.awt.Font("Papyrus", 0, 14)); // NOI18N

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Turno:"));

        __chkTurno1Sal.setText("Turno 1");
        __chkTurno1Sal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                __chkTurno1SalActionPerformed(evt);
            }
        });

        __chkTurno2Sal.setText("Turno 2");
        __chkTurno2Sal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                __chkTurno2SalActionPerformed(evt);
            }
        });

        __chkTurno3Sal.setText("Turno 3");
        __chkTurno3Sal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                __chkTurno3SalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(__chkTurno3Sal)
                    .addComponent(__chkTurno2Sal)
                    .addComponent(__chkTurno1Sal))
                .addGap(28, 28, 28))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(__chkTurno1Sal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(__chkTurno2Sal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(__chkTurno3Sal))
        );

        __tablaSalida.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "#", "Clave de Papel", "Cantidad", "Tipo de Salida", " Presentación", "Costo (Kg/Millar)", "Total"
            }
        ));
        jScrollPane2.setViewportView(__tablaSalida);

        __ACEPTARSALIDA.setText("Aceptar");

        __CANCELARSALIDA.setText("Cancelar");
        __CANCELARSALIDA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                __CANCELARSALIDAActionPerformed(evt);
            }
        });

        __SALIRSALIDA.setText("Salir");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(__cmdPropietarioSal, 0, 108, Short.MAX_VALUE)
                                    .addComponent(__etqNoMoviSal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel10))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(___OrdenCompraSal, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(__OrdenProduccionSal, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(__etqFechaSal))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(__ACEPTARSALIDA)
                .addGap(18, 18, 18)
                .addComponent(__CANCELARSALIDA)
                .addGap(18, 18, 18)
                .addComponent(__SALIRSALIDA)
                .addGap(36, 36, 36))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel8))
                            .addComponent(__etqNoMoviSal, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(__OrdenProduccionSal, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(___OrdenCompraSal, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(__cmdPropietarioSal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(14, 14, 14))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(__etqFechaSal)
                        .addGap(26, 26, 26)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(__ACEPTARSALIDA)
                    .addComponent(__CANCELARSALIDA)
                    .addComponent(__SALIRSALIDA))
                .addGap(14, 14, 14))
        );

        panel2.addTab("2. Salidas", jPanel2);

        __etqFechaDev.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        __etqFechaDev.setText("DD/MM/AAAA");

        jLabel12.setFont(new java.awt.Font("Papyrus", 1, 24)); // NOI18N
        jLabel12.setText("Devolución de Papel");

        jLabel13.setFont(new java.awt.Font("Papyrus", 0, 14)); // NOI18N
        jLabel13.setText("No. de Movimiento");

        __etqNoMoviDev.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        __cmbTipoPapelDev.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecciona....." }));
        __cmbTipoPapelDev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                __cmbTipoPapelDevActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Papyrus", 0, 14)); // NOI18N
        jLabel14.setText("Propietario:");

        jLabel15.setFont(new java.awt.Font("Papyrus", 0, 14)); // NOI18N
        jLabel15.setText("Orden de Compra:");

        jLabel16.setFont(new java.awt.Font("Papyrus", 0, 14)); // NOI18N
        jLabel16.setText("Orden de Producción:");

        __OrdenProduccionDev.setFont(new java.awt.Font("Papyrus", 0, 14)); // NOI18N

        __OrdenCompraDev.setFont(new java.awt.Font("Papyrus", 0, 14)); // NOI18N

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Turno:"));

        __chkTurno1Dev.setText("Turno 1");
        __chkTurno1Dev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                __chkTurno1DevActionPerformed(evt);
            }
        });

        __chkTurno2Dev.setText("Turno 2");
        __chkTurno2Dev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                __chkTurno2DevActionPerformed(evt);
            }
        });

        __chkTurno3Dev.setText("Turno 3");
        __chkTurno3Dev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                __chkTurno3DevActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(__chkTurno3Dev)
                    .addComponent(__chkTurno2Dev)
                    .addComponent(__chkTurno1Dev))
                .addGap(28, 28, 28))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(__chkTurno1Dev)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(__chkTurno2Dev)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(__chkTurno3Dev))
        );

        __tablaDevoluciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "#", "Clave de Papel", "Cantidad", "Tipo de Devolucion", " Presentación", "Costo (Kg/Millar)", "Total"
            }
        ));
        jScrollPane3.setViewportView(__tablaDevoluciones);

        __ACEPTARDEVOLUCIONES.setText("Aceptar");

        __CANCELARDEVOLUCIONES.setText("Cancelar");
        __CANCELARDEVOLUCIONES.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                __CANCELARDEVOLUCIONESActionPerformed(evt);
            }
        });

        __SALIRDEVOLUCIONES.setText("Salir");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel13))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(__cmbTipoPapelDev, 0, 108, Short.MAX_VALUE)
                                    .addComponent(__etqNoMoviDev, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel15))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(__OrdenCompraDev, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(__OrdenProduccionDev, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(__etqFechaDev))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(__ACEPTARDEVOLUCIONES)
                .addGap(18, 18, 18)
                .addComponent(__CANCELARDEVOLUCIONES)
                .addGap(18, 18, 18)
                .addComponent(__SALIRDEVOLUCIONES)
                .addGap(36, 36, 36))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel13))
                            .addComponent(__etqNoMoviDev, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(__OrdenProduccionDev, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(__OrdenCompraDev, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15)
                            .addComponent(__cmbTipoPapelDev, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))
                        .addGap(14, 14, 14))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(__etqFechaDev)
                        .addGap(26, 26, 26)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(__ACEPTARDEVOLUCIONES)
                    .addComponent(__CANCELARDEVOLUCIONES)
                    .addComponent(__SALIRDEVOLUCIONES))
                .addGap(14, 14, 14))
        );

        panel2.addTab("3. Devoluciones", jPanel3);

        jMenu1.setText("Archivo");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0));
        jMenuItem1.setText("Regresar al menú anterior");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem12.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem12.setText("Alta de Papel");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem12);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setText("Consultas");
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Generar un reporte...");
        jMenu1.add(jMenuItem3);

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_W, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem4.setText("Cerrar Sesion");
        jMenu1.add(jMenuItem4);

        jMenuItem5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_W, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem5.setText("Salir del Sistema");
        jMenu1.add(jMenuItem5);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edicion");

        jMenuItem6.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem6.setText("Cambiar Fecha del Sistema");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem6);

        jMenuItem7.setText("Nuevo Usuario...");
        jMenu2.add(jMenuItem7);

        jMenuItem8.setText("Cambiar mi Contraseña");
        jMenu2.add(jMenuItem8);

        jMenuItem9.setText("Reporte de Usuarios");
        jMenu2.add(jMenuItem9);

        jMenuItem10.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        jMenuItem10.setText("Ayuda");
        jMenu2.add(jMenuItem10);

        jMenuItem11.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F10, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem11.setText("Acerca de...");
        jMenu2.add(jMenuItem11);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel2)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel2)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void __cmbPropietarioEntrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event___cmbPropietarioEntrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event___cmbPropietarioEntrActionPerformed

    private void __chkTurno1EntrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event___chkTurno1EntrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event___chkTurno1EntrActionPerformed

    private void __chkTurno2EntrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event___chkTurno2EntrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event___chkTurno2EntrActionPerformed

    private void __chkTurno3EntrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event___chkTurno3EntrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event___chkTurno3EntrActionPerformed

    private void __CANCELARENTRADAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event___CANCELARENTRADAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event___CANCELARENTRADAActionPerformed

    private void __cmdPropietarioSalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event___cmdPropietarioSalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event___cmdPropietarioSalActionPerformed

    private void __chkTurno1SalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event___chkTurno1SalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event___chkTurno1SalActionPerformed

    private void __chkTurno2SalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event___chkTurno2SalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event___chkTurno2SalActionPerformed

    private void __chkTurno3SalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event___chkTurno3SalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event___chkTurno3SalActionPerformed

    private void __CANCELARSALIDAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event___CANCELARSALIDAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event___CANCELARSALIDAActionPerformed

    private void __cmbTipoPapelDevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event___cmbTipoPapelDevActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event___cmbTipoPapelDevActionPerformed

    private void __chkTurno1DevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event___chkTurno1DevActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event___chkTurno1DevActionPerformed

    private void __chkTurno2DevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event___chkTurno2DevActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event___chkTurno2DevActionPerformed

    private void __chkTurno3DevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event___chkTurno3DevActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event___chkTurno3DevActionPerformed

    private void __CANCELARDEVOLUCIONESActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event___CANCELARDEVOLUCIONESActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event___CANCELARDEVOLUCIONESActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MovimientosPapel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MovimientosPapel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MovimientosPapel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MovimientosPapel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MovimientosPapel().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton __ACEPTARDEVOLUCIONES;
    private javax.swing.JButton __ACEPTARENTRADA;
    private javax.swing.JButton __ACEPTARSALIDA;
    private javax.swing.JButton __CANCELARDEVOLUCIONES;
    private javax.swing.JButton __CANCELARENTRADA;
    private javax.swing.JButton __CANCELARSALIDA;
    private javax.swing.JTextField __OrdenCompraDev;
    private javax.swing.JTextField __OrdenCompraEntr;
    private javax.swing.JTextField __OrdenProduccionDev;
    private javax.swing.JTextField __OrdenProduccionEntr;
    private javax.swing.JTextField __OrdenProduccionSal;
    private javax.swing.JButton __SALIRDEVOLUCIONES;
    private javax.swing.JButton __SALIRENTRADA;
    private javax.swing.JButton __SALIRSALIDA;
    private javax.swing.JTextField ___OrdenCompraSal;
    private javax.swing.JCheckBox __chkTurno1Dev;
    private javax.swing.JCheckBox __chkTurno1Entr;
    private javax.swing.JCheckBox __chkTurno1Sal;
    private javax.swing.JCheckBox __chkTurno2Dev;
    private javax.swing.JCheckBox __chkTurno2Entr;
    private javax.swing.JCheckBox __chkTurno2Sal;
    private javax.swing.JCheckBox __chkTurno3Dev;
    private javax.swing.JCheckBox __chkTurno3Entr;
    private javax.swing.JCheckBox __chkTurno3Sal;
    private javax.swing.JComboBox __cmbPropietarioEntr;
    private javax.swing.JComboBox __cmbTipoPapelDev;
    private javax.swing.JComboBox __cmdPropietarioSal;
    private javax.swing.JLabel __etqFechaDev;
    private javax.swing.JLabel __etqFechaEnt;
    private javax.swing.JLabel __etqFechaSal;
    private javax.swing.JLabel __etqNoMoviDev;
    private javax.swing.JLabel __etqNoMoviEntr;
    private javax.swing.JLabel __etqNoMoviSal;
    private javax.swing.JTable __tablaDevoluciones;
    private javax.swing.JTable __tablaEntrada;
    private javax.swing.JTable __tablaSalida;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane panel2;
    // End of variables declaration//GEN-END:variables
}
